
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `MetodosPago` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model MetodosPago
 * 
 */
export type MetodosPagoModel = runtime.Types.Result.DefaultSelection<Prisma.$MetodosPagoPayload>

export type AggregateMetodosPago = {
  _count: MetodosPagoCountAggregateOutputType | null
  _avg: MetodosPagoAvgAggregateOutputType | null
  _sum: MetodosPagoSumAggregateOutputType | null
  _min: MetodosPagoMinAggregateOutputType | null
  _max: MetodosPagoMaxAggregateOutputType | null
}

export type MetodosPagoAvgAggregateOutputType = {
  id: number | null
  comprador_id: number | null
}

export type MetodosPagoSumAggregateOutputType = {
  id: number | null
  comprador_id: number | null
}

export type MetodosPagoMinAggregateOutputType = {
  id: number | null
  comprador_id: number | null
  tipo: $Enums.TipoMetodoPago | null
  nombre_provider: string | null
  token_externo: string | null
  es_predeterminado: boolean | null
}

export type MetodosPagoMaxAggregateOutputType = {
  id: number | null
  comprador_id: number | null
  tipo: $Enums.TipoMetodoPago | null
  nombre_provider: string | null
  token_externo: string | null
  es_predeterminado: boolean | null
}

export type MetodosPagoCountAggregateOutputType = {
  id: number
  comprador_id: number
  tipo: number
  nombre_provider: number
  token_externo: number
  es_predeterminado: number
  _all: number
}


export type MetodosPagoAvgAggregateInputType = {
  id?: true
  comprador_id?: true
}

export type MetodosPagoSumAggregateInputType = {
  id?: true
  comprador_id?: true
}

export type MetodosPagoMinAggregateInputType = {
  id?: true
  comprador_id?: true
  tipo?: true
  nombre_provider?: true
  token_externo?: true
  es_predeterminado?: true
}

export type MetodosPagoMaxAggregateInputType = {
  id?: true
  comprador_id?: true
  tipo?: true
  nombre_provider?: true
  token_externo?: true
  es_predeterminado?: true
}

export type MetodosPagoCountAggregateInputType = {
  id?: true
  comprador_id?: true
  tipo?: true
  nombre_provider?: true
  token_externo?: true
  es_predeterminado?: true
  _all?: true
}

export type MetodosPagoAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MetodosPago to aggregate.
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MetodosPagos to fetch.
   */
  orderBy?: Prisma.MetodosPagoOrderByWithRelationInput | Prisma.MetodosPagoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MetodosPagoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MetodosPagos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MetodosPagos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MetodosPagos
  **/
  _count?: true | MetodosPagoCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MetodosPagoAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MetodosPagoSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MetodosPagoMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MetodosPagoMaxAggregateInputType
}

export type GetMetodosPagoAggregateType<T extends MetodosPagoAggregateArgs> = {
      [P in keyof T & keyof AggregateMetodosPago]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMetodosPago[P]>
    : Prisma.GetScalarType<T[P], AggregateMetodosPago[P]>
}




export type MetodosPagoGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MetodosPagoWhereInput
  orderBy?: Prisma.MetodosPagoOrderByWithAggregationInput | Prisma.MetodosPagoOrderByWithAggregationInput[]
  by: Prisma.MetodosPagoScalarFieldEnum[] | Prisma.MetodosPagoScalarFieldEnum
  having?: Prisma.MetodosPagoScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MetodosPagoCountAggregateInputType | true
  _avg?: MetodosPagoAvgAggregateInputType
  _sum?: MetodosPagoSumAggregateInputType
  _min?: MetodosPagoMinAggregateInputType
  _max?: MetodosPagoMaxAggregateInputType
}

export type MetodosPagoGroupByOutputType = {
  id: number
  comprador_id: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo: string | null
  es_predeterminado: boolean
  _count: MetodosPagoCountAggregateOutputType | null
  _avg: MetodosPagoAvgAggregateOutputType | null
  _sum: MetodosPagoSumAggregateOutputType | null
  _min: MetodosPagoMinAggregateOutputType | null
  _max: MetodosPagoMaxAggregateOutputType | null
}

export type GetMetodosPagoGroupByPayload<T extends MetodosPagoGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MetodosPagoGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MetodosPagoGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MetodosPagoGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MetodosPagoGroupByOutputType[P]>
      }
    >
  >



export type MetodosPagoWhereInput = {
  AND?: Prisma.MetodosPagoWhereInput | Prisma.MetodosPagoWhereInput[]
  OR?: Prisma.MetodosPagoWhereInput[]
  NOT?: Prisma.MetodosPagoWhereInput | Prisma.MetodosPagoWhereInput[]
  id?: Prisma.IntFilter<"MetodosPago"> | number
  comprador_id?: Prisma.IntFilter<"MetodosPago"> | number
  tipo?: Prisma.EnumTipoMetodoPagoFilter<"MetodosPago"> | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFilter<"MetodosPago"> | string
  token_externo?: Prisma.StringNullableFilter<"MetodosPago"> | string | null
  es_predeterminado?: Prisma.BoolFilter<"MetodosPago"> | boolean
  Comprador?: Prisma.XOR<Prisma.CompradoresScalarRelationFilter, Prisma.CompradoresWhereInput>
  transacciones?: Prisma.TransaccionesListRelationFilter
}

export type MetodosPagoOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  nombre_provider?: Prisma.SortOrder
  token_externo?: Prisma.SortOrderInput | Prisma.SortOrder
  es_predeterminado?: Prisma.SortOrder
  Comprador?: Prisma.CompradoresOrderByWithRelationInput
  transacciones?: Prisma.TransaccionesOrderByRelationAggregateInput
}

export type MetodosPagoWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.MetodosPagoWhereInput | Prisma.MetodosPagoWhereInput[]
  OR?: Prisma.MetodosPagoWhereInput[]
  NOT?: Prisma.MetodosPagoWhereInput | Prisma.MetodosPagoWhereInput[]
  comprador_id?: Prisma.IntFilter<"MetodosPago"> | number
  tipo?: Prisma.EnumTipoMetodoPagoFilter<"MetodosPago"> | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFilter<"MetodosPago"> | string
  token_externo?: Prisma.StringNullableFilter<"MetodosPago"> | string | null
  es_predeterminado?: Prisma.BoolFilter<"MetodosPago"> | boolean
  Comprador?: Prisma.XOR<Prisma.CompradoresScalarRelationFilter, Prisma.CompradoresWhereInput>
  transacciones?: Prisma.TransaccionesListRelationFilter
}, "id">

export type MetodosPagoOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  nombre_provider?: Prisma.SortOrder
  token_externo?: Prisma.SortOrderInput | Prisma.SortOrder
  es_predeterminado?: Prisma.SortOrder
  _count?: Prisma.MetodosPagoCountOrderByAggregateInput
  _avg?: Prisma.MetodosPagoAvgOrderByAggregateInput
  _max?: Prisma.MetodosPagoMaxOrderByAggregateInput
  _min?: Prisma.MetodosPagoMinOrderByAggregateInput
  _sum?: Prisma.MetodosPagoSumOrderByAggregateInput
}

export type MetodosPagoScalarWhereWithAggregatesInput = {
  AND?: Prisma.MetodosPagoScalarWhereWithAggregatesInput | Prisma.MetodosPagoScalarWhereWithAggregatesInput[]
  OR?: Prisma.MetodosPagoScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MetodosPagoScalarWhereWithAggregatesInput | Prisma.MetodosPagoScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"MetodosPago"> | number
  comprador_id?: Prisma.IntWithAggregatesFilter<"MetodosPago"> | number
  tipo?: Prisma.EnumTipoMetodoPagoWithAggregatesFilter<"MetodosPago"> | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringWithAggregatesFilter<"MetodosPago"> | string
  token_externo?: Prisma.StringNullableWithAggregatesFilter<"MetodosPago"> | string | null
  es_predeterminado?: Prisma.BoolWithAggregatesFilter<"MetodosPago"> | boolean
}

export type MetodosPagoCreateInput = {
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
  Comprador: Prisma.CompradoresCreateNestedOneWithoutMetodosPagoInput
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutMetodoPagoInput
}

export type MetodosPagoUncheckedCreateInput = {
  id?: number
  comprador_id: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutMetodoPagoInput
}

export type MetodosPagoUpdateInput = {
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Comprador?: Prisma.CompradoresUpdateOneRequiredWithoutMetodosPagoNestedInput
  transacciones?: Prisma.TransaccionesUpdateManyWithoutMetodoPagoNestedInput
}

export type MetodosPagoUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  comprador_id?: Prisma.IntFieldUpdateOperationsInput | number
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutMetodoPagoNestedInput
}

export type MetodosPagoCreateManyInput = {
  id?: number
  comprador_id: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
}

export type MetodosPagoUpdateManyMutationInput = {
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MetodosPagoUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  comprador_id?: Prisma.IntFieldUpdateOperationsInput | number
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MetodosPagoCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  nombre_provider?: Prisma.SortOrder
  token_externo?: Prisma.SortOrder
  es_predeterminado?: Prisma.SortOrder
}

export type MetodosPagoAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
}

export type MetodosPagoMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  nombre_provider?: Prisma.SortOrder
  token_externo?: Prisma.SortOrder
  es_predeterminado?: Prisma.SortOrder
}

export type MetodosPagoMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
  tipo?: Prisma.SortOrder
  nombre_provider?: Prisma.SortOrder
  token_externo?: Prisma.SortOrder
  es_predeterminado?: Prisma.SortOrder
}

export type MetodosPagoSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  comprador_id?: Prisma.SortOrder
}

export type MetodosPagoListRelationFilter = {
  every?: Prisma.MetodosPagoWhereInput
  some?: Prisma.MetodosPagoWhereInput
  none?: Prisma.MetodosPagoWhereInput
}

export type MetodosPagoOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MetodosPagoScalarRelationFilter = {
  is?: Prisma.MetodosPagoWhereInput
  isNot?: Prisma.MetodosPagoWhereInput
}

export type EnumTipoMetodoPagoFieldUpdateOperationsInput = {
  set?: $Enums.TipoMetodoPago
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type MetodosPagoCreateNestedManyWithoutCompradorInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput> | Prisma.MetodosPagoCreateWithoutCompradorInput[] | Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput[]
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput | Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput[]
  createMany?: Prisma.MetodosPagoCreateManyCompradorInputEnvelope
  connect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
}

export type MetodosPagoUncheckedCreateNestedManyWithoutCompradorInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput> | Prisma.MetodosPagoCreateWithoutCompradorInput[] | Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput[]
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput | Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput[]
  createMany?: Prisma.MetodosPagoCreateManyCompradorInputEnvelope
  connect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
}

export type MetodosPagoUpdateManyWithoutCompradorNestedInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput> | Prisma.MetodosPagoCreateWithoutCompradorInput[] | Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput[]
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput | Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput[]
  upsert?: Prisma.MetodosPagoUpsertWithWhereUniqueWithoutCompradorInput | Prisma.MetodosPagoUpsertWithWhereUniqueWithoutCompradorInput[]
  createMany?: Prisma.MetodosPagoCreateManyCompradorInputEnvelope
  set?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  disconnect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  delete?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  connect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  update?: Prisma.MetodosPagoUpdateWithWhereUniqueWithoutCompradorInput | Prisma.MetodosPagoUpdateWithWhereUniqueWithoutCompradorInput[]
  updateMany?: Prisma.MetodosPagoUpdateManyWithWhereWithoutCompradorInput | Prisma.MetodosPagoUpdateManyWithWhereWithoutCompradorInput[]
  deleteMany?: Prisma.MetodosPagoScalarWhereInput | Prisma.MetodosPagoScalarWhereInput[]
}

export type MetodosPagoUncheckedUpdateManyWithoutCompradorNestedInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput> | Prisma.MetodosPagoCreateWithoutCompradorInput[] | Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput[]
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput | Prisma.MetodosPagoCreateOrConnectWithoutCompradorInput[]
  upsert?: Prisma.MetodosPagoUpsertWithWhereUniqueWithoutCompradorInput | Prisma.MetodosPagoUpsertWithWhereUniqueWithoutCompradorInput[]
  createMany?: Prisma.MetodosPagoCreateManyCompradorInputEnvelope
  set?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  disconnect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  delete?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  connect?: Prisma.MetodosPagoWhereUniqueInput | Prisma.MetodosPagoWhereUniqueInput[]
  update?: Prisma.MetodosPagoUpdateWithWhereUniqueWithoutCompradorInput | Prisma.MetodosPagoUpdateWithWhereUniqueWithoutCompradorInput[]
  updateMany?: Prisma.MetodosPagoUpdateManyWithWhereWithoutCompradorInput | Prisma.MetodosPagoUpdateManyWithWhereWithoutCompradorInput[]
  deleteMany?: Prisma.MetodosPagoScalarWhereInput | Prisma.MetodosPagoScalarWhereInput[]
}

export type MetodosPagoCreateNestedOneWithoutTransaccionesInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedCreateWithoutTransaccionesInput>
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutTransaccionesInput
  connect?: Prisma.MetodosPagoWhereUniqueInput
}

export type MetodosPagoUpdateOneRequiredWithoutTransaccionesNestedInput = {
  create?: Prisma.XOR<Prisma.MetodosPagoCreateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedCreateWithoutTransaccionesInput>
  connectOrCreate?: Prisma.MetodosPagoCreateOrConnectWithoutTransaccionesInput
  upsert?: Prisma.MetodosPagoUpsertWithoutTransaccionesInput
  connect?: Prisma.MetodosPagoWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MetodosPagoUpdateToOneWithWhereWithoutTransaccionesInput, Prisma.MetodosPagoUpdateWithoutTransaccionesInput>, Prisma.MetodosPagoUncheckedUpdateWithoutTransaccionesInput>
}

export type MetodosPagoCreateWithoutCompradorInput = {
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
  transacciones?: Prisma.TransaccionesCreateNestedManyWithoutMetodoPagoInput
}

export type MetodosPagoUncheckedCreateWithoutCompradorInput = {
  id?: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
  transacciones?: Prisma.TransaccionesUncheckedCreateNestedManyWithoutMetodoPagoInput
}

export type MetodosPagoCreateOrConnectWithoutCompradorInput = {
  where: Prisma.MetodosPagoWhereUniqueInput
  create: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput>
}

export type MetodosPagoCreateManyCompradorInputEnvelope = {
  data: Prisma.MetodosPagoCreateManyCompradorInput | Prisma.MetodosPagoCreateManyCompradorInput[]
  skipDuplicates?: boolean
}

export type MetodosPagoUpsertWithWhereUniqueWithoutCompradorInput = {
  where: Prisma.MetodosPagoWhereUniqueInput
  update: Prisma.XOR<Prisma.MetodosPagoUpdateWithoutCompradorInput, Prisma.MetodosPagoUncheckedUpdateWithoutCompradorInput>
  create: Prisma.XOR<Prisma.MetodosPagoCreateWithoutCompradorInput, Prisma.MetodosPagoUncheckedCreateWithoutCompradorInput>
}

export type MetodosPagoUpdateWithWhereUniqueWithoutCompradorInput = {
  where: Prisma.MetodosPagoWhereUniqueInput
  data: Prisma.XOR<Prisma.MetodosPagoUpdateWithoutCompradorInput, Prisma.MetodosPagoUncheckedUpdateWithoutCompradorInput>
}

export type MetodosPagoUpdateManyWithWhereWithoutCompradorInput = {
  where: Prisma.MetodosPagoScalarWhereInput
  data: Prisma.XOR<Prisma.MetodosPagoUpdateManyMutationInput, Prisma.MetodosPagoUncheckedUpdateManyWithoutCompradorInput>
}

export type MetodosPagoScalarWhereInput = {
  AND?: Prisma.MetodosPagoScalarWhereInput | Prisma.MetodosPagoScalarWhereInput[]
  OR?: Prisma.MetodosPagoScalarWhereInput[]
  NOT?: Prisma.MetodosPagoScalarWhereInput | Prisma.MetodosPagoScalarWhereInput[]
  id?: Prisma.IntFilter<"MetodosPago"> | number
  comprador_id?: Prisma.IntFilter<"MetodosPago"> | number
  tipo?: Prisma.EnumTipoMetodoPagoFilter<"MetodosPago"> | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFilter<"MetodosPago"> | string
  token_externo?: Prisma.StringNullableFilter<"MetodosPago"> | string | null
  es_predeterminado?: Prisma.BoolFilter<"MetodosPago"> | boolean
}

export type MetodosPagoCreateWithoutTransaccionesInput = {
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
  Comprador: Prisma.CompradoresCreateNestedOneWithoutMetodosPagoInput
}

export type MetodosPagoUncheckedCreateWithoutTransaccionesInput = {
  id?: number
  comprador_id: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
}

export type MetodosPagoCreateOrConnectWithoutTransaccionesInput = {
  where: Prisma.MetodosPagoWhereUniqueInput
  create: Prisma.XOR<Prisma.MetodosPagoCreateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedCreateWithoutTransaccionesInput>
}

export type MetodosPagoUpsertWithoutTransaccionesInput = {
  update: Prisma.XOR<Prisma.MetodosPagoUpdateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedUpdateWithoutTransaccionesInput>
  create: Prisma.XOR<Prisma.MetodosPagoCreateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedCreateWithoutTransaccionesInput>
  where?: Prisma.MetodosPagoWhereInput
}

export type MetodosPagoUpdateToOneWithWhereWithoutTransaccionesInput = {
  where?: Prisma.MetodosPagoWhereInput
  data: Prisma.XOR<Prisma.MetodosPagoUpdateWithoutTransaccionesInput, Prisma.MetodosPagoUncheckedUpdateWithoutTransaccionesInput>
}

export type MetodosPagoUpdateWithoutTransaccionesInput = {
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  Comprador?: Prisma.CompradoresUpdateOneRequiredWithoutMetodosPagoNestedInput
}

export type MetodosPagoUncheckedUpdateWithoutTransaccionesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  comprador_id?: Prisma.IntFieldUpdateOperationsInput | number
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type MetodosPagoCreateManyCompradorInput = {
  id?: number
  tipo: $Enums.TipoMetodoPago
  nombre_provider: string
  token_externo?: string | null
  es_predeterminado?: boolean
}

export type MetodosPagoUpdateWithoutCompradorInput = {
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transacciones?: Prisma.TransaccionesUpdateManyWithoutMetodoPagoNestedInput
}

export type MetodosPagoUncheckedUpdateWithoutCompradorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
  transacciones?: Prisma.TransaccionesUncheckedUpdateManyWithoutMetodoPagoNestedInput
}

export type MetodosPagoUncheckedUpdateManyWithoutCompradorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  tipo?: Prisma.EnumTipoMetodoPagoFieldUpdateOperationsInput | $Enums.TipoMetodoPago
  nombre_provider?: Prisma.StringFieldUpdateOperationsInput | string
  token_externo?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  es_predeterminado?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type MetodosPagoCountOutputType
 */

export type MetodosPagoCountOutputType = {
  transacciones: number
}

export type MetodosPagoCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  transacciones?: boolean | MetodosPagoCountOutputTypeCountTransaccionesArgs
}

/**
 * MetodosPagoCountOutputType without action
 */
export type MetodosPagoCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPagoCountOutputType
   */
  select?: Prisma.MetodosPagoCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MetodosPagoCountOutputType without action
 */
export type MetodosPagoCountOutputTypeCountTransaccionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TransaccionesWhereInput
}


export type MetodosPagoSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comprador_id?: boolean
  tipo?: boolean
  nombre_provider?: boolean
  token_externo?: boolean
  es_predeterminado?: boolean
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
  transacciones?: boolean | Prisma.MetodosPago$transaccionesArgs<ExtArgs>
  _count?: boolean | Prisma.MetodosPagoCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["metodosPago"]>

export type MetodosPagoSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comprador_id?: boolean
  tipo?: boolean
  nombre_provider?: boolean
  token_externo?: boolean
  es_predeterminado?: boolean
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
}, ExtArgs["result"]["metodosPago"]>

export type MetodosPagoSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  comprador_id?: boolean
  tipo?: boolean
  nombre_provider?: boolean
  token_externo?: boolean
  es_predeterminado?: boolean
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
}, ExtArgs["result"]["metodosPago"]>

export type MetodosPagoSelectScalar = {
  id?: boolean
  comprador_id?: boolean
  tipo?: boolean
  nombre_provider?: boolean
  token_externo?: boolean
  es_predeterminado?: boolean
}

export type MetodosPagoOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "comprador_id" | "tipo" | "nombre_provider" | "token_externo" | "es_predeterminado", ExtArgs["result"]["metodosPago"]>
export type MetodosPagoInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
  transacciones?: boolean | Prisma.MetodosPago$transaccionesArgs<ExtArgs>
  _count?: boolean | Prisma.MetodosPagoCountOutputTypeDefaultArgs<ExtArgs>
}
export type MetodosPagoIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
}
export type MetodosPagoIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  Comprador?: boolean | Prisma.CompradoresDefaultArgs<ExtArgs>
}

export type $MetodosPagoPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MetodosPago"
  objects: {
    Comprador: Prisma.$CompradoresPayload<ExtArgs>
    transacciones: Prisma.$TransaccionesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    comprador_id: number
    tipo: $Enums.TipoMetodoPago
    nombre_provider: string
    token_externo: string | null
    es_predeterminado: boolean
  }, ExtArgs["result"]["metodosPago"]>
  composites: {}
}

export type MetodosPagoGetPayload<S extends boolean | null | undefined | MetodosPagoDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload, S>

export type MetodosPagoCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MetodosPagoFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MetodosPagoCountAggregateInputType | true
  }

export interface MetodosPagoDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MetodosPago'], meta: { name: 'MetodosPago' } }
  /**
   * Find zero or one MetodosPago that matches the filter.
   * @param {MetodosPagoFindUniqueArgs} args - Arguments to find a MetodosPago
   * @example
   * // Get one MetodosPago
   * const metodosPago = await prisma.metodosPago.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MetodosPagoFindUniqueArgs>(args: Prisma.SelectSubset<T, MetodosPagoFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MetodosPago that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MetodosPagoFindUniqueOrThrowArgs} args - Arguments to find a MetodosPago
   * @example
   * // Get one MetodosPago
   * const metodosPago = await prisma.metodosPago.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MetodosPagoFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MetodosPagoFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MetodosPago that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoFindFirstArgs} args - Arguments to find a MetodosPago
   * @example
   * // Get one MetodosPago
   * const metodosPago = await prisma.metodosPago.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MetodosPagoFindFirstArgs>(args?: Prisma.SelectSubset<T, MetodosPagoFindFirstArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MetodosPago that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoFindFirstOrThrowArgs} args - Arguments to find a MetodosPago
   * @example
   * // Get one MetodosPago
   * const metodosPago = await prisma.metodosPago.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MetodosPagoFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MetodosPagoFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MetodosPagos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MetodosPagos
   * const metodosPagos = await prisma.metodosPago.findMany()
   * 
   * // Get first 10 MetodosPagos
   * const metodosPagos = await prisma.metodosPago.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const metodosPagoWithIdOnly = await prisma.metodosPago.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MetodosPagoFindManyArgs>(args?: Prisma.SelectSubset<T, MetodosPagoFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MetodosPago.
   * @param {MetodosPagoCreateArgs} args - Arguments to create a MetodosPago.
   * @example
   * // Create one MetodosPago
   * const MetodosPago = await prisma.metodosPago.create({
   *   data: {
   *     // ... data to create a MetodosPago
   *   }
   * })
   * 
   */
  create<T extends MetodosPagoCreateArgs>(args: Prisma.SelectSubset<T, MetodosPagoCreateArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MetodosPagos.
   * @param {MetodosPagoCreateManyArgs} args - Arguments to create many MetodosPagos.
   * @example
   * // Create many MetodosPagos
   * const metodosPago = await prisma.metodosPago.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MetodosPagoCreateManyArgs>(args?: Prisma.SelectSubset<T, MetodosPagoCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many MetodosPagos and returns the data saved in the database.
   * @param {MetodosPagoCreateManyAndReturnArgs} args - Arguments to create many MetodosPagos.
   * @example
   * // Create many MetodosPagos
   * const metodosPago = await prisma.metodosPago.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many MetodosPagos and only return the `id`
   * const metodosPagoWithIdOnly = await prisma.metodosPago.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MetodosPagoCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MetodosPagoCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a MetodosPago.
   * @param {MetodosPagoDeleteArgs} args - Arguments to delete one MetodosPago.
   * @example
   * // Delete one MetodosPago
   * const MetodosPago = await prisma.metodosPago.delete({
   *   where: {
   *     // ... filter to delete one MetodosPago
   *   }
   * })
   * 
   */
  delete<T extends MetodosPagoDeleteArgs>(args: Prisma.SelectSubset<T, MetodosPagoDeleteArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MetodosPago.
   * @param {MetodosPagoUpdateArgs} args - Arguments to update one MetodosPago.
   * @example
   * // Update one MetodosPago
   * const metodosPago = await prisma.metodosPago.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MetodosPagoUpdateArgs>(args: Prisma.SelectSubset<T, MetodosPagoUpdateArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MetodosPagos.
   * @param {MetodosPagoDeleteManyArgs} args - Arguments to filter MetodosPagos to delete.
   * @example
   * // Delete a few MetodosPagos
   * const { count } = await prisma.metodosPago.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MetodosPagoDeleteManyArgs>(args?: Prisma.SelectSubset<T, MetodosPagoDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MetodosPagos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MetodosPagos
   * const metodosPago = await prisma.metodosPago.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MetodosPagoUpdateManyArgs>(args: Prisma.SelectSubset<T, MetodosPagoUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MetodosPagos and returns the data updated in the database.
   * @param {MetodosPagoUpdateManyAndReturnArgs} args - Arguments to update many MetodosPagos.
   * @example
   * // Update many MetodosPagos
   * const metodosPago = await prisma.metodosPago.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more MetodosPagos and only return the `id`
   * const metodosPagoWithIdOnly = await prisma.metodosPago.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MetodosPagoUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MetodosPagoUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one MetodosPago.
   * @param {MetodosPagoUpsertArgs} args - Arguments to update or create a MetodosPago.
   * @example
   * // Update or create a MetodosPago
   * const metodosPago = await prisma.metodosPago.upsert({
   *   create: {
   *     // ... data to create a MetodosPago
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MetodosPago we want to update
   *   }
   * })
   */
  upsert<T extends MetodosPagoUpsertArgs>(args: Prisma.SelectSubset<T, MetodosPagoUpsertArgs<ExtArgs>>): Prisma.Prisma__MetodosPagoClient<runtime.Types.Result.GetResult<Prisma.$MetodosPagoPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of MetodosPagos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoCountArgs} args - Arguments to filter MetodosPagos to count.
   * @example
   * // Count the number of MetodosPagos
   * const count = await prisma.metodosPago.count({
   *   where: {
   *     // ... the filter for the MetodosPagos we want to count
   *   }
   * })
  **/
  count<T extends MetodosPagoCountArgs>(
    args?: Prisma.Subset<T, MetodosPagoCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MetodosPagoCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MetodosPago.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MetodosPagoAggregateArgs>(args: Prisma.Subset<T, MetodosPagoAggregateArgs>): Prisma.PrismaPromise<GetMetodosPagoAggregateType<T>>

  /**
   * Group by MetodosPago.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MetodosPagoGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MetodosPagoGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MetodosPagoGroupByArgs['orderBy'] }
      : { orderBy?: MetodosPagoGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MetodosPagoGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMetodosPagoGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MetodosPago model
 */
readonly fields: MetodosPagoFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MetodosPago.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MetodosPagoClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  Comprador<T extends Prisma.CompradoresDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CompradoresDefaultArgs<ExtArgs>>): Prisma.Prisma__CompradoresClient<runtime.Types.Result.GetResult<Prisma.$CompradoresPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  transacciones<T extends Prisma.MetodosPago$transaccionesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MetodosPago$transaccionesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TransaccionesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MetodosPago model
 */
export interface MetodosPagoFieldRefs {
  readonly id: Prisma.FieldRef<"MetodosPago", 'Int'>
  readonly comprador_id: Prisma.FieldRef<"MetodosPago", 'Int'>
  readonly tipo: Prisma.FieldRef<"MetodosPago", 'TipoMetodoPago'>
  readonly nombre_provider: Prisma.FieldRef<"MetodosPago", 'String'>
  readonly token_externo: Prisma.FieldRef<"MetodosPago", 'String'>
  readonly es_predeterminado: Prisma.FieldRef<"MetodosPago", 'Boolean'>
}
    

// Custom InputTypes
/**
 * MetodosPago findUnique
 */
export type MetodosPagoFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter, which MetodosPago to fetch.
   */
  where: Prisma.MetodosPagoWhereUniqueInput
}

/**
 * MetodosPago findUniqueOrThrow
 */
export type MetodosPagoFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter, which MetodosPago to fetch.
   */
  where: Prisma.MetodosPagoWhereUniqueInput
}

/**
 * MetodosPago findFirst
 */
export type MetodosPagoFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter, which MetodosPago to fetch.
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MetodosPagos to fetch.
   */
  orderBy?: Prisma.MetodosPagoOrderByWithRelationInput | Prisma.MetodosPagoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MetodosPagos.
   */
  cursor?: Prisma.MetodosPagoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MetodosPagos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MetodosPagos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MetodosPagos.
   */
  distinct?: Prisma.MetodosPagoScalarFieldEnum | Prisma.MetodosPagoScalarFieldEnum[]
}

/**
 * MetodosPago findFirstOrThrow
 */
export type MetodosPagoFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter, which MetodosPago to fetch.
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MetodosPagos to fetch.
   */
  orderBy?: Prisma.MetodosPagoOrderByWithRelationInput | Prisma.MetodosPagoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MetodosPagos.
   */
  cursor?: Prisma.MetodosPagoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MetodosPagos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MetodosPagos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MetodosPagos.
   */
  distinct?: Prisma.MetodosPagoScalarFieldEnum | Prisma.MetodosPagoScalarFieldEnum[]
}

/**
 * MetodosPago findMany
 */
export type MetodosPagoFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter, which MetodosPagos to fetch.
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MetodosPagos to fetch.
   */
  orderBy?: Prisma.MetodosPagoOrderByWithRelationInput | Prisma.MetodosPagoOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MetodosPagos.
   */
  cursor?: Prisma.MetodosPagoWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MetodosPagos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MetodosPagos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MetodosPagos.
   */
  distinct?: Prisma.MetodosPagoScalarFieldEnum | Prisma.MetodosPagoScalarFieldEnum[]
}

/**
 * MetodosPago create
 */
export type MetodosPagoCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * The data needed to create a MetodosPago.
   */
  data: Prisma.XOR<Prisma.MetodosPagoCreateInput, Prisma.MetodosPagoUncheckedCreateInput>
}

/**
 * MetodosPago createMany
 */
export type MetodosPagoCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MetodosPagos.
   */
  data: Prisma.MetodosPagoCreateManyInput | Prisma.MetodosPagoCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * MetodosPago createManyAndReturn
 */
export type MetodosPagoCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * The data used to create many MetodosPagos.
   */
  data: Prisma.MetodosPagoCreateManyInput | Prisma.MetodosPagoCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * MetodosPago update
 */
export type MetodosPagoUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * The data needed to update a MetodosPago.
   */
  data: Prisma.XOR<Prisma.MetodosPagoUpdateInput, Prisma.MetodosPagoUncheckedUpdateInput>
  /**
   * Choose, which MetodosPago to update.
   */
  where: Prisma.MetodosPagoWhereUniqueInput
}

/**
 * MetodosPago updateMany
 */
export type MetodosPagoUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MetodosPagos.
   */
  data: Prisma.XOR<Prisma.MetodosPagoUpdateManyMutationInput, Prisma.MetodosPagoUncheckedUpdateManyInput>
  /**
   * Filter which MetodosPagos to update
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * Limit how many MetodosPagos to update.
   */
  limit?: number
}

/**
 * MetodosPago updateManyAndReturn
 */
export type MetodosPagoUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * The data used to update MetodosPagos.
   */
  data: Prisma.XOR<Prisma.MetodosPagoUpdateManyMutationInput, Prisma.MetodosPagoUncheckedUpdateManyInput>
  /**
   * Filter which MetodosPagos to update
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * Limit how many MetodosPagos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * MetodosPago upsert
 */
export type MetodosPagoUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * The filter to search for the MetodosPago to update in case it exists.
   */
  where: Prisma.MetodosPagoWhereUniqueInput
  /**
   * In case the MetodosPago found by the `where` argument doesn't exist, create a new MetodosPago with this data.
   */
  create: Prisma.XOR<Prisma.MetodosPagoCreateInput, Prisma.MetodosPagoUncheckedCreateInput>
  /**
   * In case the MetodosPago was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MetodosPagoUpdateInput, Prisma.MetodosPagoUncheckedUpdateInput>
}

/**
 * MetodosPago delete
 */
export type MetodosPagoDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
  /**
   * Filter which MetodosPago to delete.
   */
  where: Prisma.MetodosPagoWhereUniqueInput
}

/**
 * MetodosPago deleteMany
 */
export type MetodosPagoDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MetodosPagos to delete
   */
  where?: Prisma.MetodosPagoWhereInput
  /**
   * Limit how many MetodosPagos to delete.
   */
  limit?: number
}

/**
 * MetodosPago.transacciones
 */
export type MetodosPago$transaccionesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Transacciones
   */
  select?: Prisma.TransaccionesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Transacciones
   */
  omit?: Prisma.TransaccionesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TransaccionesInclude<ExtArgs> | null
  where?: Prisma.TransaccionesWhereInput
  orderBy?: Prisma.TransaccionesOrderByWithRelationInput | Prisma.TransaccionesOrderByWithRelationInput[]
  cursor?: Prisma.TransaccionesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TransaccionesScalarFieldEnum | Prisma.TransaccionesScalarFieldEnum[]
}

/**
 * MetodosPago without action
 */
export type MetodosPagoDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MetodosPago
   */
  select?: Prisma.MetodosPagoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MetodosPago
   */
  omit?: Prisma.MetodosPagoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MetodosPagoInclude<ExtArgs> | null
}
