
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Administradores: 'Administradores',
  Compradores: 'Compradores',
  Libros: 'Libros',
  Proveedores: 'Proveedores',
  TiposUsuario: 'TiposUsuario',
  ListaProveedor: 'ListaProveedor',
  Usuarios: 'Usuarios',
  Carritos: 'Carritos',
  DetallesCarrito: 'DetallesCarrito'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdministradoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type AdministradoresScalarFieldEnum = (typeof AdministradoresScalarFieldEnum)[keyof typeof AdministradoresScalarFieldEnum]


export const CompradoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type CompradoresScalarFieldEnum = (typeof CompradoresScalarFieldEnum)[keyof typeof CompradoresScalarFieldEnum]


export const LibrosScalarFieldEnum = {
  id: 'id',
  isbn: 'isbn',
  nombre: 'nombre',
  autor: 'autor',
  precio: 'precio',
  stock: 'stock',
  estado: 'estado'
} as const

export type LibrosScalarFieldEnum = (typeof LibrosScalarFieldEnum)[keyof typeof LibrosScalarFieldEnum]


export const ProveedoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type ProveedoresScalarFieldEnum = (typeof ProveedoresScalarFieldEnum)[keyof typeof ProveedoresScalarFieldEnum]


export const TiposUsuarioScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre'
} as const

export type TiposUsuarioScalarFieldEnum = (typeof TiposUsuarioScalarFieldEnum)[keyof typeof TiposUsuarioScalarFieldEnum]


export const ListaProveedorScalarFieldEnum = {
  id: 'id',
  usuario_id: 'usuario_id',
  es_proveedor: 'es_proveedor',
  fecha_solicitud: 'fecha_solicitud'
} as const

export type ListaProveedorScalarFieldEnum = (typeof ListaProveedorScalarFieldEnum)[keyof typeof ListaProveedorScalarFieldEnum]


export const UsuariosScalarFieldEnum = {
  id: 'id',
  email: 'email',
  contrasena: 'contrasena',
  nombre: 'nombre',
  apellido: 'apellido',
  direccion: 'direccion',
  tipo_usuario_id: 'tipo_usuario_id'
} as const

export type UsuariosScalarFieldEnum = (typeof UsuariosScalarFieldEnum)[keyof typeof UsuariosScalarFieldEnum]


export const CarritosScalarFieldEnum = {
  id: 'id',
  comprador_id: 'comprador_id',
  precio_total: 'precio_total'
} as const

export type CarritosScalarFieldEnum = (typeof CarritosScalarFieldEnum)[keyof typeof CarritosScalarFieldEnum]


export const DetallesCarritoScalarFieldEnum = {
  id: 'id',
  carrito_id: 'carrito_id',
  libro_id: 'libro_id',
  cantidad: 'cantidad',
  precio: 'precio'
} as const

export type DetallesCarritoScalarFieldEnum = (typeof DetallesCarritoScalarFieldEnum)[keyof typeof DetallesCarritoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

