
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Administradores: 'Administradores',
  Compradores: 'Compradores',
  Libros: 'Libros',
  Proveedores: 'Proveedores',
  TiposUsuario: 'TiposUsuario',
  ListaProveedor: 'ListaProveedor',
  Usuarios: 'Usuarios',
  Carritos: 'Carritos',
  DetallesCarrito: 'DetallesCarrito'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "administradores" | "compradores" | "libros" | "proveedores" | "tiposUsuario" | "listaProveedor" | "usuarios" | "carritos" | "detallesCarrito"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Administradores: {
      payload: Prisma.$AdministradoresPayload<ExtArgs>
      fields: Prisma.AdministradoresFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AdministradoresFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AdministradoresFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        findFirst: {
          args: Prisma.AdministradoresFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AdministradoresFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        findMany: {
          args: Prisma.AdministradoresFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>[]
        }
        create: {
          args: Prisma.AdministradoresCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        createMany: {
          args: Prisma.AdministradoresCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AdministradoresCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>[]
        }
        delete: {
          args: Prisma.AdministradoresDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        update: {
          args: Prisma.AdministradoresUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        deleteMany: {
          args: Prisma.AdministradoresDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AdministradoresUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AdministradoresUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>[]
        }
        upsert: {
          args: Prisma.AdministradoresUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AdministradoresPayload>
        }
        aggregate: {
          args: Prisma.AdministradoresAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAdministradores>
        }
        groupBy: {
          args: Prisma.AdministradoresGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdministradoresGroupByOutputType>[]
        }
        count: {
          args: Prisma.AdministradoresCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AdministradoresCountAggregateOutputType> | number
        }
      }
    }
    Compradores: {
      payload: Prisma.$CompradoresPayload<ExtArgs>
      fields: Prisma.CompradoresFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CompradoresFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CompradoresFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        findFirst: {
          args: Prisma.CompradoresFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CompradoresFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        findMany: {
          args: Prisma.CompradoresFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>[]
        }
        create: {
          args: Prisma.CompradoresCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        createMany: {
          args: Prisma.CompradoresCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CompradoresCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>[]
        }
        delete: {
          args: Prisma.CompradoresDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        update: {
          args: Prisma.CompradoresUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        deleteMany: {
          args: Prisma.CompradoresDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CompradoresUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CompradoresUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>[]
        }
        upsert: {
          args: Prisma.CompradoresUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompradoresPayload>
        }
        aggregate: {
          args: Prisma.CompradoresAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCompradores>
        }
        groupBy: {
          args: Prisma.CompradoresGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompradoresGroupByOutputType>[]
        }
        count: {
          args: Prisma.CompradoresCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CompradoresCountAggregateOutputType> | number
        }
      }
    }
    Libros: {
      payload: Prisma.$LibrosPayload<ExtArgs>
      fields: Prisma.LibrosFieldRefs
      operations: {
        findUnique: {
          args: Prisma.LibrosFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.LibrosFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        findFirst: {
          args: Prisma.LibrosFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.LibrosFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        findMany: {
          args: Prisma.LibrosFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>[]
        }
        create: {
          args: Prisma.LibrosCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        createMany: {
          args: Prisma.LibrosCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.LibrosCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>[]
        }
        delete: {
          args: Prisma.LibrosDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        update: {
          args: Prisma.LibrosUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        deleteMany: {
          args: Prisma.LibrosDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.LibrosUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.LibrosUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>[]
        }
        upsert: {
          args: Prisma.LibrosUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$LibrosPayload>
        }
        aggregate: {
          args: Prisma.LibrosAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateLibros>
        }
        groupBy: {
          args: Prisma.LibrosGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LibrosGroupByOutputType>[]
        }
        count: {
          args: Prisma.LibrosCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.LibrosCountAggregateOutputType> | number
        }
      }
    }
    Proveedores: {
      payload: Prisma.$ProveedoresPayload<ExtArgs>
      fields: Prisma.ProveedoresFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProveedoresFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProveedoresFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        findFirst: {
          args: Prisma.ProveedoresFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProveedoresFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        findMany: {
          args: Prisma.ProveedoresFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>[]
        }
        create: {
          args: Prisma.ProveedoresCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        createMany: {
          args: Prisma.ProveedoresCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProveedoresCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>[]
        }
        delete: {
          args: Prisma.ProveedoresDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        update: {
          args: Prisma.ProveedoresUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        deleteMany: {
          args: Prisma.ProveedoresDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProveedoresUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProveedoresUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>[]
        }
        upsert: {
          args: Prisma.ProveedoresUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProveedoresPayload>
        }
        aggregate: {
          args: Prisma.ProveedoresAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProveedores>
        }
        groupBy: {
          args: Prisma.ProveedoresGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProveedoresGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProveedoresCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProveedoresCountAggregateOutputType> | number
        }
      }
    }
    TiposUsuario: {
      payload: Prisma.$TiposUsuarioPayload<ExtArgs>
      fields: Prisma.TiposUsuarioFieldRefs
      operations: {
        findUnique: {
          args: Prisma.TiposUsuarioFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.TiposUsuarioFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        findFirst: {
          args: Prisma.TiposUsuarioFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.TiposUsuarioFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        findMany: {
          args: Prisma.TiposUsuarioFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>[]
        }
        create: {
          args: Prisma.TiposUsuarioCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        createMany: {
          args: Prisma.TiposUsuarioCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.TiposUsuarioCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>[]
        }
        delete: {
          args: Prisma.TiposUsuarioDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        update: {
          args: Prisma.TiposUsuarioUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        deleteMany: {
          args: Prisma.TiposUsuarioDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.TiposUsuarioUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.TiposUsuarioUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>[]
        }
        upsert: {
          args: Prisma.TiposUsuarioUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$TiposUsuarioPayload>
        }
        aggregate: {
          args: Prisma.TiposUsuarioAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateTiposUsuario>
        }
        groupBy: {
          args: Prisma.TiposUsuarioGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiposUsuarioGroupByOutputType>[]
        }
        count: {
          args: Prisma.TiposUsuarioCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.TiposUsuarioCountAggregateOutputType> | number
        }
      }
    }
    ListaProveedor: {
      payload: Prisma.$ListaProveedorPayload<ExtArgs>
      fields: Prisma.ListaProveedorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ListaProveedorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ListaProveedorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        findFirst: {
          args: Prisma.ListaProveedorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ListaProveedorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        findMany: {
          args: Prisma.ListaProveedorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>[]
        }
        create: {
          args: Prisma.ListaProveedorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        createMany: {
          args: Prisma.ListaProveedorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ListaProveedorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>[]
        }
        delete: {
          args: Prisma.ListaProveedorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        update: {
          args: Prisma.ListaProveedorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        deleteMany: {
          args: Prisma.ListaProveedorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ListaProveedorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ListaProveedorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>[]
        }
        upsert: {
          args: Prisma.ListaProveedorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ListaProveedorPayload>
        }
        aggregate: {
          args: Prisma.ListaProveedorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateListaProveedor>
        }
        groupBy: {
          args: Prisma.ListaProveedorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ListaProveedorGroupByOutputType>[]
        }
        count: {
          args: Prisma.ListaProveedorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ListaProveedorCountAggregateOutputType> | number
        }
      }
    }
    Usuarios: {
      payload: Prisma.$UsuariosPayload<ExtArgs>
      fields: Prisma.UsuariosFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UsuariosFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UsuariosFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        findFirst: {
          args: Prisma.UsuariosFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UsuariosFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        findMany: {
          args: Prisma.UsuariosFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>[]
        }
        create: {
          args: Prisma.UsuariosCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        createMany: {
          args: Prisma.UsuariosCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.UsuariosCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>[]
        }
        delete: {
          args: Prisma.UsuariosDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        update: {
          args: Prisma.UsuariosUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        deleteMany: {
          args: Prisma.UsuariosDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UsuariosUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.UsuariosUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>[]
        }
        upsert: {
          args: Prisma.UsuariosUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UsuariosPayload>
        }
        aggregate: {
          args: Prisma.UsuariosAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUsuarios>
        }
        groupBy: {
          args: Prisma.UsuariosGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsuariosGroupByOutputType>[]
        }
        count: {
          args: Prisma.UsuariosCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UsuariosCountAggregateOutputType> | number
        }
      }
    }
    Carritos: {
      payload: Prisma.$CarritosPayload<ExtArgs>
      fields: Prisma.CarritosFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CarritosFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CarritosFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        findFirst: {
          args: Prisma.CarritosFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CarritosFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        findMany: {
          args: Prisma.CarritosFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>[]
        }
        create: {
          args: Prisma.CarritosCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        createMany: {
          args: Prisma.CarritosCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CarritosCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>[]
        }
        delete: {
          args: Prisma.CarritosDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        update: {
          args: Prisma.CarritosUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        deleteMany: {
          args: Prisma.CarritosDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CarritosUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CarritosUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>[]
        }
        upsert: {
          args: Prisma.CarritosUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CarritosPayload>
        }
        aggregate: {
          args: Prisma.CarritosAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCarritos>
        }
        groupBy: {
          args: Prisma.CarritosGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CarritosGroupByOutputType>[]
        }
        count: {
          args: Prisma.CarritosCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CarritosCountAggregateOutputType> | number
        }
      }
    }
    DetallesCarrito: {
      payload: Prisma.$DetallesCarritoPayload<ExtArgs>
      fields: Prisma.DetallesCarritoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DetallesCarritoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DetallesCarritoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        findFirst: {
          args: Prisma.DetallesCarritoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DetallesCarritoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        findMany: {
          args: Prisma.DetallesCarritoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>[]
        }
        create: {
          args: Prisma.DetallesCarritoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        createMany: {
          args: Prisma.DetallesCarritoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DetallesCarritoCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>[]
        }
        delete: {
          args: Prisma.DetallesCarritoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        update: {
          args: Prisma.DetallesCarritoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        deleteMany: {
          args: Prisma.DetallesCarritoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DetallesCarritoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DetallesCarritoUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>[]
        }
        upsert: {
          args: Prisma.DetallesCarritoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DetallesCarritoPayload>
        }
        aggregate: {
          args: Prisma.DetallesCarritoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDetallesCarrito>
        }
        groupBy: {
          args: Prisma.DetallesCarritoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DetallesCarritoGroupByOutputType>[]
        }
        count: {
          args: Prisma.DetallesCarritoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DetallesCarritoCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const AdministradoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type AdministradoresScalarFieldEnum = (typeof AdministradoresScalarFieldEnum)[keyof typeof AdministradoresScalarFieldEnum]


export const CompradoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type CompradoresScalarFieldEnum = (typeof CompradoresScalarFieldEnum)[keyof typeof CompradoresScalarFieldEnum]


export const LibrosScalarFieldEnum = {
  id: 'id',
  isbn: 'isbn',
  nombre: 'nombre',
  autor: 'autor',
  precio: 'precio',
  stock: 'stock',
  estado: 'estado'
} as const

export type LibrosScalarFieldEnum = (typeof LibrosScalarFieldEnum)[keyof typeof LibrosScalarFieldEnum]


export const ProveedoresScalarFieldEnum = {
  usuario_id: 'usuario_id'
} as const

export type ProveedoresScalarFieldEnum = (typeof ProveedoresScalarFieldEnum)[keyof typeof ProveedoresScalarFieldEnum]


export const TiposUsuarioScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre'
} as const

export type TiposUsuarioScalarFieldEnum = (typeof TiposUsuarioScalarFieldEnum)[keyof typeof TiposUsuarioScalarFieldEnum]


export const ListaProveedorScalarFieldEnum = {
  id: 'id',
  usuario_id: 'usuario_id',
  es_proveedor: 'es_proveedor',
  fecha_solicitud: 'fecha_solicitud'
} as const

export type ListaProveedorScalarFieldEnum = (typeof ListaProveedorScalarFieldEnum)[keyof typeof ListaProveedorScalarFieldEnum]


export const UsuariosScalarFieldEnum = {
  id: 'id',
  email: 'email',
  contrasena: 'contrasena',
  nombre: 'nombre',
  apellido: 'apellido',
  direccion: 'direccion',
  tipo_usuario_id: 'tipo_usuario_id'
} as const

export type UsuariosScalarFieldEnum = (typeof UsuariosScalarFieldEnum)[keyof typeof UsuariosScalarFieldEnum]


export const CarritosScalarFieldEnum = {
  id: 'id',
  comprador_id: 'comprador_id',
  precio_total: 'precio_total'
} as const

export type CarritosScalarFieldEnum = (typeof CarritosScalarFieldEnum)[keyof typeof CarritosScalarFieldEnum]


export const DetallesCarritoScalarFieldEnum = {
  id: 'id',
  carrito_id: 'carrito_id',
  libro_id: 'libro_id',
  cantidad: 'cantidad',
  precio: 'precio'
} as const

export type DetallesCarritoScalarFieldEnum = (typeof DetallesCarritoScalarFieldEnum)[keyof typeof DetallesCarritoScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'Decimal[]'
 */
export type ListDecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  administradores?: Prisma.AdministradoresOmit
  compradores?: Prisma.CompradoresOmit
  libros?: Prisma.LibrosOmit
  proveedores?: Prisma.ProveedoresOmit
  tiposUsuario?: Prisma.TiposUsuarioOmit
  listaProveedor?: Prisma.ListaProveedorOmit
  usuarios?: Prisma.UsuariosOmit
  carritos?: Prisma.CarritosOmit
  detallesCarrito?: Prisma.DetallesCarritoOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

