
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Administradores.ts'
export type * from './models/Compradores.ts'
export type * from './models/Libros.ts'
export type * from './models/Proveedores.ts'
export type * from './models/Usuarios.ts'
export type * from './models/OfertaLibro.ts'
export type * from './commonInputTypes.ts'