
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Administradores.js'
export type * from './models/Compradores.js'
export type * from './models/Libros.js'
export type * from './models/Proveedores.js'
export type * from './models/Usuarios.js'
export type * from './commonInputTypes.js'